system:
    default:
        field_templates:
            - { template: '@ezdesign/fieldtype/currency_view.html.twig', priority: 1 }
            - { template: '@ezdesign/fieldtype/language_view.html.twig', priority: 1 }
            - { template: '@ezdesign/fieldtype/timezone_view.html.twig', priority: 1 }
            - { template: '@ezdesign/fieldtype/locale_view.html.twig', priority: 1 }
        fielddefinition_edit_templates:
            - { template: "@ezdesign/fieldtype/currency_definition_edit.html.twig", priority: 1 }
            - { template: "@ezdesign/fieldtype/language_definition_edit.html.twig", priority: 1 }
            - { template: "@ezdesign/fieldtype/timezone_definition_edit.html.twig", priority: 1 }
            - { template: "@ezdesign/fieldtype/locale_definition_edit.html.twig", priority: 1 }
