imports:
    - { resource: fieldtype/ezcalcval.yaml }
    - { resource: fieldtype/ezcurrency.yaml }
    - { resource: fieldtype/ezentity.yaml }
    - { resource: fieldtype/ezlanguage.yaml }
    - { resource: fieldtype/ezlocale.yaml }
    - { resource: fieldtype/ezmaskedtextline.yaml }
    - { resource: fieldtype/eztimezone.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformFieldTypeLibrary\Core\MVC\Symfony\Templating\FallbackFieldBlockRenderer:
        decorates: ezpublish.templating.field_block_renderer.twig

    AdamWojs\EzPlatformFieldTypeLibrary\API\FieldType\AbstractChoice\ChoiceProviderRegistry:
        arguments:
            $fieldTypeRegistry: '@eZ\Publish\Core\FieldType\FieldTypeRegistry'

    ### Maker

    AdamWojs\EzPlatformFieldTypeLibraryBundle\Maker\MakeChoiceFieldType:
        tags:
            - { name: maker.command }

    AdamWojs\EzPlatformFieldTypeLibraryBundle\Maker\MakeTextLineFieldType:
        tags:
            - { name: maker.command }

    AdamWojs\EzPlatformFieldTypeLibraryBundle\Maker\MakeEntityFieldType:
        arguments:
            $doctrineHelper: '@maker.doctrine_helper'
        tags:
            - { name: maker.command }
