services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformFieldTypeLibrary\Core\FieldType\AbstractEntity\Doctrine\Behavior\AssociableWithContentSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber }
