services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezplatform.field_type.ezmaskedtextline:
        class: AdamWojs\EzPlatformFieldTypeLibrary\Core\FieldType\MaskedTextLine\Type
        arguments:
            $format: '@ezplatform.field_type.ezmaskedtextline.format'
        tags:
            - { name: ezplatform.field_type, alias: ezmaskedtextline }

    ezplatform.field_type.ezmaskedtextline.format:
        class: AdamWojs\EzPlatformFieldTypeLibrary\API\FieldType\AbstractTextLine\MaskedTextLineFormat

    ezplatform.field_type.ezmaskedtextline.converter:
        class: AdamWojs\EzPlatformFieldTypeLibrary\Core\Persistence\Legacy\Converter\MaskedTextLineConverter
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: ezmaskedtextline }

    ezplatform.field_type.ezmaskedtextline.indexable:
        class: AdamWojs\EzPlatformFieldTypeLibrary\Core\FieldType\AbstractTextLine\SearchField
        tags:
            - { name: ezplatform.field_type.indexable, alias: ezmaskedtextline }

    ezplatform.field_type.ezmaskedtextline.form_mapper.value:
        class: AdamWojs\EzPlatformFieldTypeLibrary\Core\FieldType\MaskedTextLine\FormMapper\FieldValueFormMapper
        arguments:
            $format: '@ezplatform.field_type.ezmaskedtextline.format'
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezmaskedtextline }

    ezplatform.field_type.ezmaskedtextline.form_mapper.definition:
        class: AdamWojs\EzPlatformFieldTypeLibrary\Core\FieldType\MaskedTextLine\FormMapper\FieldDefinitionFormMapper
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: ezmaskedtextline }

